### ISSUE TITLE
Trying to compile on windows 11 (QT5.15, Graphviz3.0)

### ISSUE THREAD

**Issue by Frozaccio** [Gepetto/qgv#13]
Hello,
Thanks for the good work, I am interested in using graphviz inside QT.
Unfortunately, I have a link error, but I do not think it comes from the windows, QT or graphviz versions. There is a library I cannot find and I do not know what this library is:

main.obj:-1: error: LNK2019: unresolved external symbol "public: static struct QMetaObject const QGVScene::staticMetaObject" (?staticMetaObject@QGVScene@@2UQMetaObject@@B) referenced in function "public: static class QString __cdecl QGVScene::tr(char const *,char const *,int)" (?tr@QGVScene@@SA?AVQString@@PEBD0H@Z)

MainWindow.obj:-1: error: LNK2001: unresolved external symbol "public: static struct QMetaObject const QGVScene::staticMetaObject" (?staticMetaObject@QGVScene@@2UQMetaObject@@B)

Any idea where it comes from?

**Comment by qingshan-z** [comment]
I have encountered the same problem, how can I solve it

**Comment by nim65s** [comment]
Hi,

I guess tihs is a visibility issue.
I can't provide windows support, but PR are welcome.

Simplest workaround would be for you to try this under WSL
